# 可选基础镜像 ubuntu:22.04, ubuntu:20.04, ubuntu:18.04
FROM ubuntu:latest

# 阻止交互式提示
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    zip \
    gcc \
    gdb \
    g++ \
    wget \
    curl \
    unzip \
    cmake \
    lrzsz \
    clang \
    openssl \
    autoconf \
    xz-utils \
    libunwind8 \
    libssl-dev \
    libicu-dev \
    libkrb5-dev \
    build-essential

# 安装 Boost
RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2 \
    && tar -xjf boost_1_84_0.tar.bz2 \
    && rm boost_1_84_0.tar.bz2 \
    && cd boost_1_84_0/ \
    && ./bootstrap.sh \
    && ./b2 cxxflags=-fPIC \
    && ./b2 install --prefix=/usr \
    && cd .. \
    && rm -rf boost_1_84_0/

# 构建 jemalloc
RUN wget https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2 \
    && tar -xjf jemalloc-5.3.0.tar.bz2 \
    && rm jemalloc-5.3.0.tar.bz2 \
    && cd jemalloc-5.3.0 \
    && ./autogen.sh --with-jemalloc-prefix=je_ \
    && make -j$(nproc) \
    && make install_bin install_include install_lib \
    && cd .. \
    && rm -rf jemalloc-5.3.0/

# 构建 OpenSSL
RUN wget https://www.openssl.org/source/openssl-3.0.13.tar.gz \
    && tar -xzf openssl-3.0.13.tar.gz \
    && rm openssl-3.0.13.tar.gz \
    && cd openssl-3.0.13 \
    && ./Configure \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf openssl-3.0.13/
